spring:
  datasource:
    # 数据库配置文件
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: 123456

# mybatis打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/curiophil/javalearn/mapper/xml/*.xml
