spring:
  datasource:
    # 数据库配置文件
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12346
    url: 123465

# mybatis打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
