spring:
  jackson:
    time-zone: GMT+8
  datasource:
    # 数据库配置文件
    mysql:
      name: mysql
      # mysql8 datetime对应LocalDateTime mysql5~ datetime对应timestamp
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/java_learn?useSSL=false
    presto:
      name: presto
      driver-class-name: com.facebook.presto.jdbc.PrestoDriver
      username: default
      jdbc-url: jdbc:presto://hadoop112:9000/mysqldb/
    clickhouse:
      name: clickhouse
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      username: admin
      password: qwer1234@Q
      jdbc-url: jdbc:clickhouse://xxx/collector?use_server_time_zone=true&time_zone=Asia/Shanghai

# mybatis打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations1: classpath:com/curiophil/javalearn/mapper/mysql/xml/*.xml
  mapper-locations2: classpath:com/curiophil/javalearn/mapper/presto/xml/*.xml
  mapper-locations-clickhouse: classpath:com/curiophil/javalearn/mapper/clickhouse/xml/*.xml

rocketmq:
  name-server: hadoop102:9876
  producer:
    group: default
    send-message-timeout: 300000

# 控制台打印sql
logging:
  level:
    com.curiophil.javalearn.mapper: debug
